add versions list available in China
MCMrARM/mc-w10-version-launcher pull request #185
Opened 2022-03-04 16:54 UTC by quizhizhe

For some reasons, some github URLs cannot be accessed in China. For users who use MCLauncher in China, most of them cannot update the version list automatically. So I take the language method of identifying the system to judge whether to use Gitee in China

2022-11-09 15:14 UTC, yaosiqian requested changes
Mirror no updates

2022-11-11 12:10 UTC, yaosiqian commented
Actually, I still don't think "Official 3rd-Party Mirror for Chinese Users" is so that great.
I think it's better to make the version link configurable.

讲实话，我认为什么“中国用户专用第三方镜像”真没有好到哪里去。
_（主要还是因为只有**部分**地区会把 GitHub 的 DNS 污染）_
我觉得还是让这个链接可配置化比较好
_（自定义赛高）_

2022-11-11 12:23 UTC, quizhizhe commented
> Actually, I still don't think "Official 3rd-Party Mirror for Chinese Users" is so that great. I think it's better to make the version link configurable.
> 
> 讲实话，我认为什么“中国用户专用第三方镜像”真没有好到哪里去。 _（主要还是因为只有**部分**地区会把 GitHub 的 DNS 污染）_ 我觉得还是让这个链接可配置化比较好 _（自定义赛高）_

其实我不会C#，只能微改；其实可以自己下载文件放到根目录覆盖version.json就可以了

2022-11-11 12:59 UTC, closed without merging

2022-11-12 13:56 UTC, dktapps commented
> Actually, I still don't think "Official 3rd-Party Mirror for Chinese Users" is so that great. I think it's better to make the version link configurable.
> 
> 讲实话，我认为什么“中国用户专用第三方镜像”真没有好到哪里去。 _（主要还是因为只有**部分**地区会把 GitHub 的 DNS 污染）_ 我觉得还是让这个链接可配置化比较好 _（自定义赛高）_

+1 for this, I've meant to implement this for some time.

2022-11-12 14:05 UTC, quizhizhe commented
> > Actually, I still don't think "Official 3rd-Party Mirror for Chinese Users" is so that great. I think it's better to make the version link configurable.
> > 讲实话，我认为什么“中国用户专用第三方镜像”真没有好到哪里去。 _（主要还是因为只有**部分**地区会把 GitHub 的 DNS 污染）_ 我觉得还是让这个链接可配置化比较好 _（自定义赛高）_
> 
> +1 for this, I've meant to implement this for some time.

这个是个人用修改的，只是我一时脑热提交的pr，这个pr已经关闭，就不必再讨论这个了